"""Persistência das solicitações de desligamento."""

from __future__ import annotations

import sqlite3
from contextlib import closing
from datetime import date, datetime
from pathlib import Path
from typing import Any

from flask import current_app

from models.termination import TerminationRequest
from services.user_service import is_postgresql_url


TERMINATION_STATUSES = frozenset({"Pendente", "Desativado", "Cancelado"})


class TerminationService:
    def __init__(self, database: str | Path):
        self.database = str(database).strip()
        self.backend = "postgresql" if is_postgresql_url(self.database) else "sqlite"
        self._schema_ready = False

    def _connect(self):
        if self.backend == "sqlite":
            connection = sqlite3.connect(self.database)
            connection.row_factory = sqlite3.Row
            return connection
        try:
            import psycopg
            from psycopg.rows import dict_row
        except ImportError as error:
            raise RuntimeError(
                "O driver PostgreSQL não está instalado. Instale requirements.txt."
            ) from error
        return psycopg.connect(self.database, row_factory=dict_row)

    @property
    def _placeholder(self) -> str:
        return "%s" if self.backend == "postgresql" else "?"

    @staticmethod
    def _is_integrity_error(error: Exception) -> bool:
        return isinstance(error, sqlite3.IntegrityError) or error.__class__.__name__ in {
            "IntegrityError", "UniqueViolation"
        }

    def ensure_schema(self) -> None:
        if self._schema_ready:
            return
        with closing(self._connect()) as connection:
            if self.backend == "postgresql":
                connection.execute("""
                    CREATE TABLE IF NOT EXISTS desligamentos (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT,
                        nome TEXT NOT NULL,
                        usuario TEXT NOT NULL,
                        email TEXT NOT NULL,
                        perfil TEXT NOT NULL DEFAULT '',
                        filial TEXT NOT NULL DEFAULT '',
                        departamento TEXT NOT NULL DEFAULT '',
                        data_desligamento DATE NOT NULL,
                        observacao TEXT NOT NULL DEFAULT '',
                        status TEXT NOT NULL DEFAULT 'Pendente' CHECK (
                            status IN ('Pendente', 'Desativado', 'Cancelado')
                        ),
                        solicitado_por_id BIGINT NOT NULL,
                        solicitado_por TEXT NOT NULL,
                        solicitado_em TIMESTAMP NOT NULL,
                        desativado_por TEXT,
                        desativado_em TIMESTAMP,
                        created_at TIMESTAMP NOT NULL,
                        updated_at TIMESTAMP NOT NULL
                    )
                """)
            else:
                connection.execute("""
                    CREATE TABLE IF NOT EXISTS desligamentos (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        user_id INTEGER,
                        nome TEXT NOT NULL,
                        usuario TEXT NOT NULL,
                        email TEXT NOT NULL,
                        perfil TEXT NOT NULL DEFAULT '',
                        filial TEXT NOT NULL DEFAULT '',
                        departamento TEXT NOT NULL DEFAULT '',
                        data_desligamento TEXT NOT NULL,
                        observacao TEXT NOT NULL DEFAULT '',
                        status TEXT NOT NULL DEFAULT 'Pendente' CHECK (
                            status IN ('Pendente', 'Desativado', 'Cancelado')
                        ),
                        solicitado_por_id INTEGER NOT NULL,
                        solicitado_por TEXT NOT NULL,
                        solicitado_em TEXT NOT NULL,
                        desativado_por TEXT,
                        desativado_em TEXT,
                        created_at TEXT NOT NULL,
                        updated_at TEXT NOT NULL
                    )
                """)
            connection.execute(
                "CREATE INDEX IF NOT EXISTS desligamentos_status_idx "
                "ON desligamentos (status)"
            )
            connection.execute(
                "CREATE INDEX IF NOT EXISTS desligamentos_solicitante_idx "
                "ON desligamentos (solicitado_por_id)"
            )
            connection.execute("""
                CREATE UNIQUE INDEX IF NOT EXISTS desligamentos_pendente_user_uidx
                ON desligamentos (user_id)
                WHERE status = 'Pendente' AND user_id IS NOT NULL
            """)
            connection.commit()
        self._schema_ready = True

    def create(
        self, *, user_id: int | None, nome: str, usuario: str, email: str,
        perfil: str, filial: str, departamento: str, data_desligamento: date,
        observacao: str, solicitado_por_id: int, solicitado_por: str,
    ) -> TerminationRequest:
        if not nome.strip() or not usuario.strip():
            raise ValueError("Nome e usuário são obrigatórios.")
        self.ensure_schema()
        now = datetime.now().replace(microsecond=0)
        value_date: Any = data_desligamento
        value_now: Any = now
        if self.backend == "sqlite":
            value_date = data_desligamento.isoformat()
            value_now = now.isoformat()
        p = self._placeholder
        try:
            with closing(self._connect()) as connection:
                cursor = connection.execute(
                    f"""
                    INSERT INTO desligamentos (
                        user_id, nome, usuario, email, perfil, filial, departamento,
                        data_desligamento, observacao, status, solicitado_por_id,
                        solicitado_por, solicitado_em, created_at, updated_at
                    ) VALUES ({', '.join([p] * 15)})
                    {"RETURNING id" if self.backend == "postgresql" else ""}
                    """,
                    (
                        user_id, nome.strip(), usuario.strip(), email.strip(),
                        perfil.strip(), filial.strip(), departamento.strip(), value_date,
                        observacao.strip(), "Pendente", solicitado_por_id,
                        solicitado_por.strip(), value_now, value_now, value_now,
                    ),
                )
                if self.backend == "postgresql":
                    row = cursor.fetchone()
                    if row is None:
                        raise RuntimeError("O PostgreSQL não retornou o desligamento criado.")
                    request_id = int(row["id"])
                else:
                    if cursor.lastrowid is None:
                        raise RuntimeError("O SQLite não retornou o desligamento criado.")
                    request_id = int(cursor.lastrowid)
                connection.commit()
        except Exception as error:
            if not self._is_integrity_error(error):
                raise
            raise ValueError(
                "Já existe uma solicitação pendente para este usuário."
            ) from error
        return self._get_required(request_id)

    def get_by_id(self, request_id: int) -> TerminationRequest | None:
        self.ensure_schema()
        with closing(self._connect()) as connection:
            row = connection.execute(
                f"SELECT * FROM desligamentos WHERE id = {self._placeholder}",
                (request_id,),
            ).fetchone()
        return TerminationRequest.from_row(row) if row else None

    def _get_required(self, request_id: int) -> TerminationRequest:
        request_record = self.get_by_id(request_id)
        if request_record is None:
            raise RuntimeError("O desligamento gravado não pôde ser relido.")
        return request_record

    def list_all(
        self, *, solicitado_por_id: int | None = None, search: str = "",
        status: str = "", filial: str = "",
    ) -> list[TerminationRequest]:
        self.ensure_schema()
        conditions: list[str] = []
        values: list[Any] = []
        p = self._placeholder
        if solicitado_por_id is not None:
            conditions.append(f"solicitado_por_id = {p}")
            values.append(solicitado_por_id)
        if search.strip():
            conditions.append(
                f"LOWER(nome || ' ' || usuario || ' ' || email) LIKE LOWER({p})"
            )
            values.append(f"%{search.strip()}%")
        if status in TERMINATION_STATUSES:
            conditions.append(f"status = {p}")
            values.append(status)
        if filial.strip():
            conditions.append(f"filial = {p}")
            values.append(filial.strip())
        where = " WHERE " + " AND ".join(conditions) if conditions else ""
        with closing(self._connect()) as connection:
            rows = connection.execute(
                "SELECT * FROM desligamentos" + where
                + " ORDER BY CASE status WHEN 'Pendente' THEN 0 ELSE 1 END, "
                "data_desligamento DESC, id DESC",
                tuple(values),
            ).fetchall()
        return [TerminationRequest.from_row(row) for row in rows]

    def branches(self, *, solicitado_por_id: int | None = None) -> list[str]:
        self.ensure_schema()
        where = ""
        values: tuple[Any, ...] = ()
        if solicitado_por_id is not None:
            where = f" WHERE solicitado_por_id = {self._placeholder}"
            values = (solicitado_por_id,)
        with closing(self._connect()) as connection:
            rows = connection.execute(
                "SELECT DISTINCT filial FROM desligamentos" + where
                + " ORDER BY filial",
                values,
            ).fetchall()
        return [str(row["filial"]).strip() for row in rows if str(row["filial"]).strip()]

    def summary(self, *, solicitado_por_id: int | None = None) -> dict[str, int]:
        records = self.list_all(solicitado_por_id=solicitado_por_id)
        today = date.today()
        return {
            "pendentes": sum(item.status == "Pendente" for item in records),
            "realizados": sum(item.status == "Desativado" for item in records),
            "periodo": sum(
                item.data_desligamento.year == today.year
                and item.data_desligamento.month == today.month
                for item in records
            ),
        }

    def update_pending(
        self, request_id: int, *, user_id: int | None, nome: str, usuario: str,
        email: str, perfil: str, filial: str, departamento: str,
        data_desligamento: date, observacao: str,
    ) -> TerminationRequest:
        self.ensure_schema()
        if not nome.strip() or not usuario.strip():
            raise ValueError("Nome e usuário são obrigatórios.")
        now = datetime.now().replace(microsecond=0)
        values: list[Any] = [
            user_id, nome.strip(), usuario.strip(), email.strip(), perfil.strip(),
            filial.strip(), departamento.strip(), data_desligamento,
            observacao.strip(), now, request_id,
        ]
        if self.backend == "sqlite":
            values[7] = data_desligamento.isoformat()
            values[9] = now.isoformat()
        p = self._placeholder
        try:
            with closing(self._connect()) as connection:
                cursor = connection.execute(
                    f"""
                    UPDATE desligamentos SET user_id={p}, nome={p}, usuario={p},
                        email={p}, perfil={p}, filial={p}, departamento={p},
                        data_desligamento={p}, observacao={p}, updated_at={p}
                    WHERE id={p} AND status='Pendente'
                    """,
                    tuple(values),
                )
                connection.commit()
        except Exception as error:
            if not self._is_integrity_error(error):
                raise
            raise ValueError(
                "Já existe uma solicitação pendente para este usuário."
            ) from error
        if cursor.rowcount == 0:
            raise ValueError("Somente solicitações pendentes podem ser editadas.")
        return self._get_required(request_id)

    def associate_user(
        self, request_id: int, user_id: int
    ) -> TerminationRequest:
        """Associa com segurança um usuário a uma solicitação ainda pendente."""
        self.ensure_schema()
        now = datetime.now().replace(microsecond=0)
        value_now: Any = now if self.backend == "postgresql" else now.isoformat()
        p = self._placeholder
        try:
            with closing(self._connect()) as connection:
                cursor = connection.execute(
                    f"""
                    UPDATE desligamentos SET user_id={p}, updated_at={p}
                    WHERE id={p} AND status='Pendente' AND user_id IS NULL
                    """,
                    (user_id, value_now, request_id),
                )
                connection.commit()
        except Exception as error:
            if not self._is_integrity_error(error):
                raise
            raise ValueError(
                "Já existe uma solicitação pendente para este usuário."
            ) from error
        if cursor.rowcount == 0:
            raise ValueError(
                "A solicitação já foi associada, processada ou não existe."
            )
        return self._get_required(request_id)

    def _transition(
        self, request_id: int, status: str, *, desativado_por: str | None = None,
    ) -> TerminationRequest:
        self.ensure_schema()
        if status not in {"Desativado", "Cancelado"}:
            raise ValueError("Status de desligamento inválido.")
        now = datetime.now().replace(microsecond=0)
        value_now: Any = now if self.backend == "postgresql" else now.isoformat()
        p = self._placeholder
        with closing(self._connect()) as connection:
            cursor = connection.execute(
                f"""
                UPDATE desligamentos SET status={p}, desativado_por={p},
                    desativado_em={p}, updated_at={p}
                WHERE id={p} AND status='Pendente'
                """,
                (status, desativado_por, value_now if status == "Desativado" else None,
                 value_now, request_id),
            )
            connection.commit()
        if cursor.rowcount == 0:
            raise ValueError("A solicitação já foi processada ou não existe.")
        return self._get_required(request_id)

    def cancel(self, request_id: int) -> TerminationRequest:
        return self._transition(request_id, "Cancelado")

    def mark_deactivated(
        self, request_id: int, administrator: str,
    ) -> TerminationRequest:
        return self._transition(
            request_id, "Desativado", desativado_por=administrator
        )

    def count_pending(self) -> int:
        self.ensure_schema()
        with closing(self._connect()) as connection:
            row = connection.execute(
                "SELECT COUNT(*) AS total FROM desligamentos WHERE status='Pendente'"
            ).fetchone()
        return int(row["total"] if self.backend == "postgresql" else row[0])


def configure_termination_service(app, database: str | Path) -> None:
    service = TerminationService(database)
    service.ensure_schema()
    app.extensions["fokus_termination_service"] = service


def get_termination_service() -> TerminationService:
    service = current_app.extensions.get("fokus_termination_service")
    if service is None:
        raise RuntimeError("O serviço de desligamentos não foi inicializado.")
    return service
