"""Persistência das solicitações de desligamento."""

from __future__ import annotations

import sqlite3
from contextlib import closing
from datetime import date, datetime
from pathlib import Path
from typing import Any

from flask import current_app

from models.termination import TerminationRequest
from services.user_service import is_postgresql_url


TERMINATION_STATUSES = frozenset({"PENDENTE", "CONFIRMADO", "CANCELADO"})


class TerminationService:
    def __init__(self, database: str | Path):
        self.database = str(database).strip()
        self.backend = "postgresql" if is_postgresql_url(self.database) else "sqlite"
        self._schema_ready = False

    def _connect(self):
        if self.backend == "sqlite":
            connection = sqlite3.connect(self.database)
            connection.row_factory = sqlite3.Row
            return connection
        try:
            import psycopg
            from psycopg.rows import dict_row
        except ImportError as error:
            raise RuntimeError(
                "O driver PostgreSQL não está instalado. Instale requirements.txt."
            ) from error
        return psycopg.connect(self.database, row_factory=dict_row)

    @property
    def _placeholder(self) -> str:
        return "%s" if self.backend == "postgresql" else "?"

    @staticmethod
    def _is_integrity_error(error: Exception) -> bool:
        return isinstance(error, sqlite3.IntegrityError) or error.__class__.__name__ in {
            "IntegrityError", "UniqueViolation"
        }

    def ensure_schema(self) -> None:
        if self._schema_ready:
            return
        with closing(self._connect()) as connection:
            columns = self._table_columns(connection, "desligamentos")
            if not columns:
                self._create_table(connection, "desligamentos")
            elif "usuario_ad" not in columns or {
                "user_id", "solicitado_por_id", "usuario"
            } & columns:
                self._migrate_legacy_schema(connection, columns)
            connection.execute(
                "CREATE INDEX IF NOT EXISTS desligamentos_status_idx "
                "ON desligamentos (status)"
            )
            connection.execute(
                "CREATE INDEX IF NOT EXISTS desligamentos_data_idx "
                "ON desligamentos (data_desligamento)"
            )
            connection.commit()
        self._schema_ready = True

    def _table_columns(self, connection, table: str) -> set[str]:
        if self.backend == "postgresql":
            rows = connection.execute(
                "SELECT column_name FROM information_schema.columns "
                "WHERE table_schema = current_schema() AND table_name = %s",
                (table,),
            ).fetchall()
            return {str(row["column_name"]) for row in rows}
        rows = connection.execute(f"PRAGMA table_info({table})").fetchall()
        return {str(row["name"]) for row in rows}

    def _create_table(self, connection, table: str) -> None:
        id_type = (
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if self.backend == "postgresql" else "INTEGER PRIMARY KEY AUTOINCREMENT"
        )
        date_type = "DATE" if self.backend == "postgresql" else "TEXT"
        datetime_type = "TIMESTAMP" if self.backend == "postgresql" else "TEXT"
        connection.execute(f"""
            CREATE TABLE {table} (
                id {id_type},
                nome TEXT NOT NULL,
                usuario_ad TEXT NOT NULL,
                email TEXT NOT NULL,
                perfil TEXT NOT NULL DEFAULT '',
                filial TEXT NOT NULL DEFAULT '',
                departamento TEXT NOT NULL DEFAULT '',
                data_desligamento {date_type} NOT NULL,
                observacao TEXT NOT NULL DEFAULT '',
                informado_por TEXT NOT NULL,
                data_solicitacao {datetime_type} NOT NULL,
                status TEXT NOT NULL DEFAULT 'PENDENTE' CHECK (
                    status IN ('PENDENTE', 'CONFIRMADO', 'CANCELADO')
                ),
                data_confirmacao {datetime_type},
                confirmado_por TEXT,
                created_at {datetime_type} NOT NULL,
                updated_at {datetime_type} NOT NULL
            )
        """)

    def _migrate_legacy_schema(self, connection, columns: set[str]) -> None:
        """Migra registros antigos removendo todo vínculo com a tabela usuarios."""
        temporary = "desligamentos_independentes_migracao"
        connection.execute(f"DROP TABLE IF EXISTS {temporary}")
        self._create_table(connection, temporary)
        rows = connection.execute("SELECT * FROM desligamentos ORDER BY id").fetchall()
        p = self._placeholder
        for row in rows:
            item = dict(row)
            status = {
                "Pendente": "PENDENTE", "Desativado": "CONFIRMADO",
                "Cancelado": "CANCELADO",
            }.get(str(item.get("status", "")), str(item.get("status", "PENDENTE")).upper())
            data_solicitacao = item.get("data_solicitacao") or item.get("solicitado_em")
            created_at = item.get("created_at") or data_solicitacao
            updated_at = item.get("updated_at") or created_at
            connection.execute(
                f"""
                INSERT INTO {temporary} (
                    id, nome, usuario_ad, email, perfil, filial, departamento,
                    data_desligamento, observacao, informado_por, data_solicitacao,
                    status, data_confirmacao, confirmado_por, created_at, updated_at
                ) VALUES ({', '.join([p] * 16)})
                """,
                (
                    item["id"], item["nome"],
                    item.get("usuario_ad") or item.get("usuario") or "",
                    item.get("email") or "", item.get("perfil") or "",
                    item.get("filial") or "", item.get("departamento") or "",
                    item["data_desligamento"], item.get("observacao") or "",
                    item.get("informado_por") or item.get("solicitado_por") or "Sistema",
                    data_solicitacao, status,
                    item.get("data_confirmacao") or item.get("desativado_em"),
                    item.get("confirmado_por") or item.get("desativado_por"),
                    created_at, updated_at,
                ),
            )
        connection.execute("DROP TABLE desligamentos")
        connection.execute(f"ALTER TABLE {temporary} RENAME TO desligamentos")
        if self.backend == "postgresql":
            connection.execute("""
                SELECT setval(
                    pg_get_serial_sequence('desligamentos', 'id'),
                    COALESCE((SELECT MAX(id) FROM desligamentos), 1),
                    EXISTS (SELECT 1 FROM desligamentos)
                )
            """)

    def create(
        self, *, nome: str, usuario_ad: str, email: str,
        perfil: str, filial: str, departamento: str, data_desligamento: date,
        observacao: str, informado_por: str,
    ) -> TerminationRequest:
        if not nome.strip():
            raise ValueError("Nome do colaborador é obrigatório.")
        self.ensure_schema()
        now = datetime.now().replace(microsecond=0)
        value_date: Any = data_desligamento
        value_now: Any = now
        if self.backend == "sqlite":
            value_date = data_desligamento.isoformat()
            value_now = now.isoformat()
        p = self._placeholder
        try:
            with closing(self._connect()) as connection:
                cursor = connection.execute(
                    f"""
                    INSERT INTO desligamentos (
                        nome, usuario_ad, email, perfil, filial, departamento,
                        data_desligamento, observacao, informado_por, data_solicitacao,
                        status, created_at, updated_at
                    ) VALUES ({', '.join([p] * 13)})
                    {"RETURNING id" if self.backend == "postgresql" else ""}
                    """,
                    (
                        nome.strip(), usuario_ad.strip(), email.strip(),
                        perfil.strip(), filial.strip(), departamento.strip(), value_date,
                        observacao.strip(), informado_por.strip(), value_now,
                        "PENDENTE", value_now, value_now,
                    ),
                )
                if self.backend == "postgresql":
                    row = cursor.fetchone()
                    if row is None:
                        raise RuntimeError("O PostgreSQL não retornou o desligamento criado.")
                    request_id = int(row["id"])
                else:
                    if cursor.lastrowid is None:
                        raise RuntimeError("O SQLite não retornou o desligamento criado.")
                    request_id = int(cursor.lastrowid)
                connection.commit()
        except Exception as error:
            if not self._is_integrity_error(error):
                raise
            raise ValueError("Não foi possível salvar a solicitação.") from error
        return self._get_required(request_id)

    def get_by_id(self, request_id: int) -> TerminationRequest | None:
        self.ensure_schema()
        with closing(self._connect()) as connection:
            row = connection.execute(
                f"SELECT * FROM desligamentos WHERE id = {self._placeholder}",
                (request_id,),
            ).fetchone()
        return TerminationRequest.from_row(row) if row else None

    def _get_required(self, request_id: int) -> TerminationRequest:
        request_record = self.get_by_id(request_id)
        if request_record is None:
            raise RuntimeError("O desligamento gravado não pôde ser relido.")
        return request_record

    def list_all(
        self, *, search: str = "", status: str = "", filial: str = "",
    ) -> list[TerminationRequest]:
        self.ensure_schema()
        conditions: list[str] = []
        values: list[Any] = []
        p = self._placeholder
        if search.strip():
            conditions.append(
                f"LOWER(nome || ' ' || usuario_ad || ' ' || email) LIKE LOWER({p})"
            )
            values.append(f"%{search.strip()}%")
        if status in TERMINATION_STATUSES:
            conditions.append(f"status = {p}")
            values.append(status)
        if filial.strip():
            conditions.append(f"filial = {p}")
            values.append(filial.strip())
        where = " WHERE " + " AND ".join(conditions) if conditions else ""
        with closing(self._connect()) as connection:
            rows = connection.execute(
                "SELECT * FROM desligamentos" + where
                + " ORDER BY CASE status WHEN 'PENDENTE' THEN 0 ELSE 1 END, "
                "data_desligamento DESC, id DESC",
                tuple(values),
            ).fetchall()
        return [TerminationRequest.from_row(row) for row in rows]

    def branches(self) -> list[str]:
        self.ensure_schema()
        with closing(self._connect()) as connection:
            rows = connection.execute(
                "SELECT DISTINCT filial FROM desligamentos ORDER BY filial"
            ).fetchall()
        return [str(row["filial"]).strip() for row in rows if str(row["filial"]).strip()]

    def summary(self) -> dict[str, int]:
        records = self.list_all()
        today = date.today()
        return {
            "pendentes": sum(item.status == "PENDENTE" for item in records),
            "realizados": sum(item.status == "CONFIRMADO" for item in records),
            "periodo": sum(
                item.data_desligamento.year == today.year
                and item.data_desligamento.month == today.month
                for item in records
            ),
        }

    def update_pending(
        self, request_id: int, *, nome: str, usuario_ad: str,
        email: str, perfil: str, filial: str, departamento: str,
        data_desligamento: date, observacao: str,
    ) -> TerminationRequest:
        self.ensure_schema()
        if not nome.strip() or not usuario_ad.strip():
            raise ValueError("Nome e usuário AD são obrigatórios.")
        now = datetime.now().replace(microsecond=0)
        values: list[Any] = [
            nome.strip(), usuario_ad.strip(), email.strip(), perfil.strip(),
            filial.strip(), departamento.strip(), data_desligamento,
            observacao.strip(), now, request_id,
        ]
        if self.backend == "sqlite":
            values[6] = data_desligamento.isoformat()
            values[8] = now.isoformat()
        p = self._placeholder
        try:
            with closing(self._connect()) as connection:
                cursor = connection.execute(
                    f"""
                    UPDATE desligamentos SET nome={p}, usuario_ad={p},
                        email={p}, perfil={p}, filial={p}, departamento={p},
                        data_desligamento={p}, observacao={p}, updated_at={p}
                    WHERE id={p} AND status='PENDENTE'
                    """,
                    tuple(values),
                )
                connection.commit()
        except Exception as error:
            if not self._is_integrity_error(error):
                raise
            raise ValueError("Não foi possível atualizar a solicitação.") from error
        if cursor.rowcount == 0:
            raise ValueError("Somente solicitações pendentes podem ser editadas.")
        return self._get_required(request_id)

    def _transition(
        self, request_id: int, status: str, *, confirmado_por: str | None = None,
    ) -> TerminationRequest:
        self.ensure_schema()
        if status not in {"CONFIRMADO", "CANCELADO"}:
            raise ValueError("Status de desligamento inválido.")
        now = datetime.now().replace(microsecond=0)
        value_now: Any = now if self.backend == "postgresql" else now.isoformat()
        p = self._placeholder
        with closing(self._connect()) as connection:
            cursor = connection.execute(
                f"""
                UPDATE desligamentos SET status={p}, confirmado_por={p},
                    data_confirmacao={p}, updated_at={p}
                WHERE id={p} AND status='PENDENTE'
                """,
                (status, confirmado_por, value_now if status == "CONFIRMADO" else None,
                 value_now, request_id),
            )
            connection.commit()
        if cursor.rowcount == 0:
            raise ValueError("A solicitação já foi processada ou não existe.")
        return self._get_required(request_id)

    def cancel(self, request_id: int) -> TerminationRequest:
        return self._transition(request_id, "CANCELADO")

    def confirm(
        self, request_id: int, administrator: str,
    ) -> TerminationRequest:
        return self._transition(
            request_id, "CONFIRMADO", confirmado_por=administrator
        )

    def count_pending(self) -> int:
        self.ensure_schema()
        with closing(self._connect()) as connection:
            row = connection.execute(
                "SELECT COUNT(*) AS total FROM desligamentos WHERE status='PENDENTE'"
            ).fetchone()
        return int(row["total"] if self.backend == "postgresql" else row[0])


def configure_termination_service(app, database: str | Path) -> None:
    service = TerminationService(database)
    service.ensure_schema()
    app.extensions["fokus_termination_service"] = service


def get_termination_service() -> TerminationService:
    service = current_app.extensions.get("fokus_termination_service")
    if service is None:
        raise RuntimeError("O serviço de desligamentos não foi inicializado.")
    return service
