"""Persistência isolada dos usuários em SQLite ou PostgreSQL."""

from __future__ import annotations

import re
import sqlite3
from contextlib import closing
from datetime import datetime
from pathlib import Path
from typing import Any

from werkzeug.security import check_password_hash, generate_password_hash

from models.user import User


VALID_PROFILES = frozenset({"admin", "rh", "gestor", "consulta"})
EMAIL_PATTERN = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")
POSTGRES_SCHEMES = ("postgresql://", "postgres://")


def is_valid_email(email: str) -> bool:
    return bool(EMAIL_PATTERN.fullmatch(email.strip()))


class UserService:
    """Mantém o contrato de usuários independente do banco selecionado."""

    def __init__(self, database: str | Path):
        self.database = str(database)
        self.database_path = self.database  # Compatibilidade com código existente.
        self.backend = (
            "postgresql"
            if self.database.lower().startswith(POSTGRES_SCHEMES)
            else "sqlite"
        )
        self._schema_ready = False

    def _connect(self):
        if self.backend == "sqlite":
            connection = sqlite3.connect(self.database)
            connection.row_factory = sqlite3.Row
            return connection

        try:
            import psycopg
            from psycopg.rows import dict_row
        except ImportError as error:
            raise RuntimeError(
                "O driver PostgreSQL não está instalado. Instale as dependências "
                "de requirements.txt."
            ) from error
        return psycopg.connect(self.database, row_factory=dict_row)

    @property
    def _placeholder(self) -> str:
        return "%s" if self.backend == "postgresql" else "?"

    @staticmethod
    def _is_integrity_error(error: Exception) -> bool:
        return isinstance(error, sqlite3.IntegrityError) or (
            error.__class__.__name__ in {"IntegrityError", "UniqueViolation"}
        )

    def ensure_schema(self) -> bool:
        """Cria a tabela e informa se ela ainda não existia."""
        if self._schema_ready:
            return False

        if self.backend == "sqlite":
            database_path = Path(self.database)
            database_exists = database_path.exists()
            database_path.parent.mkdir(parents=True, exist_ok=True)
            with closing(self._connect()) as connection:
                if database_exists:
                    table_exists = connection.execute(
                        """
                        SELECT 1 FROM sqlite_master
                        WHERE type = 'table' AND name = 'usuarios'
                        """
                    ).fetchone()
                    if table_exists is None:
                        raise RuntimeError(
                            "O banco de usuários existente não contém a tabela "
                            "usuarios; a inicialização foi interrompida."
                        )
                    self._schema_ready = True
                    return False

                connection.execute("""
                    CREATE TABLE IF NOT EXISTS usuarios (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        nome TEXT NOT NULL,
                        usuario TEXT NOT NULL UNIQUE COLLATE NOCASE,
                        email TEXT NOT NULL UNIQUE COLLATE NOCASE,
                        senha_hash TEXT NOT NULL,
                        perfil TEXT NOT NULL CHECK (
                            perfil IN ('admin', 'rh', 'gestor', 'consulta')
                        ),
                        ativo INTEGER NOT NULL DEFAULT 1 CHECK (ativo IN (0, 1)),
                        ultimo_login TEXT,
                        created_at TEXT NOT NULL
                    )
                """)
                connection.commit()
            self._schema_ready = True
            return True

        with closing(self._connect()) as connection:
            existed_row = connection.execute(
                "SELECT to_regclass('usuarios') IS NOT NULL AS exists"
            ).fetchone()
            table_existed = bool(existed_row["exists"])
            connection.execute("""
                CREATE TABLE IF NOT EXISTS usuarios (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nome TEXT NOT NULL,
                    usuario TEXT NOT NULL,
                    email TEXT NOT NULL,
                    senha_hash TEXT NOT NULL,
                    perfil TEXT NOT NULL CHECK (
                        perfil IN ('admin', 'rh', 'gestor', 'consulta')
                    ),
                    ativo BOOLEAN NOT NULL DEFAULT TRUE,
                    ultimo_login TIMESTAMP,
                    created_at TIMESTAMP NOT NULL
                )
            """)
            connection.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS "
                "usuarios_usuario_lower_uidx ON usuarios (LOWER(usuario))"
            )
            connection.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS "
                "usuarios_email_lower_uidx ON usuarios (LOWER(email))"
            )
            connection.commit()
        self._schema_ready = True
        return not table_existed

    def initialize(self) -> bool:
        """Inicializa o serviço sem repovoar bancos existentes vazios."""
        database_created = self.ensure_schema()
        if database_created and self.backend == "sqlite":
            self.create(
                nome="Administrador",
                usuario="admin",
                email="admin@fokus.local",
                senha="admin123",
                perfil="admin",
            )
            return True

        if self.count() == 0:
            if self.backend == "postgresql":
                raise RuntimeError(
                    "O PostgreSQL de usuários está vazio. Migre o usuarios.db "
                    "antes de iniciar a aplicação em produção."
                )
            raise RuntimeError(
                "O banco de usuários existente está vazio. "
                "O administrador padrão não será recriado automaticamente."
            )
        return False

    def count(self) -> int:
        self.ensure_schema()
        with closing(self._connect()) as connection:
            row = connection.execute("SELECT COUNT(*) AS total FROM usuarios").fetchone()
        return int(row["total"] if self.backend == "postgresql" else row[0])

    def create(
        self,
        *,
        nome: str,
        usuario: str,
        email: str,
        senha: str,
        perfil: str,
        ativo: bool = True,
    ) -> User:
        if perfil not in VALID_PROFILES:
            raise ValueError("Perfil de usuário inválido.")
        if not nome.strip() or not usuario.strip() or not senha:
            raise ValueError("Nome, usuário e senha são obrigatórios.")
        if not is_valid_email(email):
            raise ValueError("Informe um e-mail válido.")
        if len(senha) < 8:
            raise ValueError("A senha deve ter no mínimo 8 caracteres.")

        self.ensure_schema()
        created_at = datetime.now().replace(microsecond=0)
        placeholder = self._placeholder
        try:
            with closing(self._connect()) as connection:
                cursor = connection.execute(
                    f"""
                    INSERT INTO usuarios (
                        nome, usuario, email, senha_hash, perfil, ativo, created_at
                    ) VALUES ({', '.join([placeholder] * 7)})
                    {"RETURNING id" if self.backend == "postgresql" else ""}
                    """,
                    (
                        nome.strip(), usuario.strip(), email.strip(),
                        generate_password_hash(senha), perfil,
                        bool(ativo) if self.backend == "postgresql" else int(ativo),
                        created_at if self.backend == "postgresql" else created_at.isoformat(),
                    ),
                )
                user_id = (
                    cursor.fetchone()["id"]
                    if self.backend == "postgresql"
                    else cursor.lastrowid
                )
                connection.commit()
        except Exception as error:
            if not self._is_integrity_error(error):
                raise
            message = str(error).lower()
            if "email" in message:
                raise ValueError("Este e-mail já está cadastrado.") from error
            if "usuario" in message:
                raise ValueError("Este usuário já está cadastrado.") from error
            raise ValueError("Não foi possível cadastrar o usuário.") from error
        return self.get_by_id(user_id)

    def _get_one(self, column: str, value: Any, *, case_insensitive=False) -> User | None:
        self.ensure_schema()
        placeholder = self._placeholder
        if case_insensitive:
            condition = (
                f"LOWER({column}) = LOWER({placeholder})"
                if self.backend == "postgresql"
                else f"{column} = {placeholder} COLLATE NOCASE"
            )
        else:
            condition = f"{column} = {placeholder}"
        with closing(self._connect()) as connection:
            row = connection.execute(
                f"SELECT * FROM usuarios WHERE {condition}", (value,)
            ).fetchone()
        return User.from_row(row) if row else None

    def get_by_id(self, user_id: int) -> User | None:
        return self._get_one("id", user_id)

    def get_by_username(self, username: str) -> User | None:
        return self._get_one("usuario", username.strip(), case_insensitive=True)

    def get_by_email(self, email: str) -> User | None:
        return self._get_one("email", email.strip(), case_insensitive=True)

    def list_all(self) -> list[User]:
        self.ensure_schema()
        order = "LOWER(nome)" if self.backend == "postgresql" else "nome COLLATE NOCASE"
        with closing(self._connect()) as connection:
            rows = connection.execute(
                f"SELECT * FROM usuarios ORDER BY ativo DESC, {order}"
            ).fetchall()
        return [User.from_row(row) for row in rows]

    def update(
        self,
        user_id: int,
        *,
        nome: str,
        email: str,
        perfil: str,
        ativo: bool,
    ) -> User:
        self.ensure_schema()
        if not nome.strip():
            raise ValueError("O nome é obrigatório.")
        if not is_valid_email(email):
            raise ValueError("Informe um e-mail válido.")
        if perfil not in VALID_PROFILES:
            raise ValueError("Perfil de usuário inválido.")
        placeholder = self._placeholder
        try:
            with closing(self._connect()) as connection:
                cursor = connection.execute(
                    f"""
                    UPDATE usuarios
                    SET nome = {placeholder}, email = {placeholder},
                        perfil = {placeholder}, ativo = {placeholder}
                    WHERE id = {placeholder}
                    """,
                    (
                        nome.strip(), email.strip(), perfil,
                        bool(ativo) if self.backend == "postgresql" else int(ativo),
                        user_id,
                    ),
                )
                connection.commit()
        except Exception as error:
            if not self._is_integrity_error(error):
                raise
            if "email" in str(error).lower():
                raise ValueError("Este e-mail já está cadastrado.") from error
            raise ValueError("Não foi possível atualizar o usuário.") from error
        if cursor.rowcount == 0:
            raise ValueError("Usuário não encontrado.")
        return self.get_by_id(user_id)

    def _update_field(self, user_id: int, field: str, value: Any) -> User:
        placeholder = self._placeholder
        with closing(self._connect()) as connection:
            cursor = connection.execute(
                f"UPDATE usuarios SET {field} = {placeholder} WHERE id = {placeholder}",
                (value, user_id),
            )
            connection.commit()
        if cursor.rowcount == 0:
            raise ValueError("Usuário não encontrado.")
        return self.get_by_id(user_id)

    def set_active(self, user_id: int, active: bool) -> User:
        self.ensure_schema()
        value = bool(active) if self.backend == "postgresql" else int(active)
        return self._update_field(user_id, "ativo", value)

    def reset_password(self, user_id: int, new_password: str) -> User:
        self.ensure_schema()
        if len(new_password) < 8:
            raise ValueError("A senha deve ter no mínimo 8 caracteres.")
        return self._update_field(
            user_id, "senha_hash", generate_password_hash(new_password)
        )

    def update_last_login(self, user_id: int) -> datetime:
        self.ensure_schema()
        moment = datetime.now().replace(microsecond=0)
        value = moment if self.backend == "postgresql" else moment.isoformat()
        self._update_field(user_id, "ultimo_login", value)
        return moment

    def change_password(
        self, user_id: int, current_password: str, new_password: str
    ) -> bool:
        if len(new_password) < 8:
            return False
        user = self.get_by_id(user_id)
        if user is None or not check_password_hash(user.senha_hash, current_password):
            return False
        self._update_field(
            user_id, "senha_hash", generate_password_hash(new_password)
        )
        return True

    def migrate_from_sqlite(self, sqlite_path: str | Path) -> int:
        """Copia usuários uma única vez, sem escrever no SQLite de origem."""
        if self.backend != "postgresql":
            raise ValueError("O destino da migração deve ser PostgreSQL.")

        source_path = Path(sqlite_path).resolve()
        if not source_path.is_file():
            raise FileNotFoundError(f"Banco SQLite não encontrado: {source_path}")
        self.ensure_schema()
        if self.count() != 0:
            raise RuntimeError(
                "A migração foi cancelada porque a tabela PostgreSQL não está vazia."
            )

        source_uri = source_path.as_uri() + "?mode=ro"
        with closing(sqlite3.connect(source_uri, uri=True)) as source:
            source.row_factory = sqlite3.Row
            table = source.execute(
                "SELECT 1 FROM sqlite_master WHERE type='table' AND name='usuarios'"
            ).fetchone()
            if table is None:
                raise RuntimeError("O SQLite de origem não contém a tabela usuarios.")
            rows = source.execute("SELECT * FROM usuarios ORDER BY id").fetchall()

        if not rows:
            raise RuntimeError("O SQLite de origem não contém usuários.")
        if not any(row["perfil"] == "admin" and bool(row["ativo"]) for row in rows):
            raise RuntimeError("A origem não contém um administrador ativo.")

        columns = (
            "id", "nome", "usuario", "email", "senha_hash", "perfil",
            "ativo", "ultimo_login", "created_at",
        )
        values = [
            tuple(
                bool(row[column]) if column == "ativo" else row[column]
                for column in columns
            )
            for row in rows
        ]
        with closing(self._connect()) as target:
            try:
                with target.cursor() as cursor:
                    cursor.executemany(
                        f"INSERT INTO usuarios ({', '.join(columns)}) VALUES "
                        f"({', '.join(['%s'] * len(columns))})",
                        values,
                    )
                target.execute("""
                    SELECT setval(
                        pg_get_serial_sequence('usuarios', 'id'),
                        (SELECT MAX(id) FROM usuarios),
                        TRUE
                    )
                """)
                migrated = target.execute(
                    "SELECT COUNT(*) AS total FROM usuarios"
                ).fetchone()["total"]
                if int(migrated) != len(rows):
                    raise RuntimeError("A conferência da migração encontrou divergências.")
                target.commit()
            except Exception:
                target.rollback()
                raise

        self._schema_ready = True
        return len(rows)
